// constants/eduData.ts
// Curated lists of Indonesian universities and study programs (prodi) for the
// searchable filters. These power autocomplete suggestions — users can still
// type anything not on the list (free text is always allowed).
//
// Common abbreviations are embedded in parentheses (e.g. "(UNS)") so a plain
// substring search — the kind Postgres `ilike` does — finds a match whether
// someone searches the full name or the short form. `UNIVERSITY_ALIASES`
// below additionally covers profiles that were saved *before* this list had
// the abbreviation baked in (or where a user typed the full name by hand).

export const UNIVERSITIES: string[] = [
  'Universitas Indonesia (UI)',
  'Universitas Gadjah Mada (UGM)',
  'Institut Teknologi Bandung (ITB)',
  'Institut Pertanian Bogor (IPB University)',
  'Institut Teknologi Sepuluh Nopember (ITS)',
  'Universitas Airlangga (UNAIR)',
  'Universitas Brawijaya (UB)',
  'Universitas Diponegoro (UNDIP)',
  'Universitas Padjadjaran (UNPAD)',
  'Universitas Sebelas Maret (UNS)',
  'Universitas Hasanuddin (UNHAS)',
  'Universitas Sumatera Utara (USU)',
  'Universitas Negeri Yogyakarta (UNY)',
  'Universitas Negeri Jakarta (UNJ)',
  'Universitas Negeri Malang (UM)',
  'Universitas Negeri Semarang (UNNES)',
  'Universitas Negeri Surabaya (UNESA)',
  'Universitas Negeri Medan (UNIMED)',
  'Universitas Negeri Padang (UNP)',
  'Universitas Negeri Makassar (UNM)',
  'Universitas Pendidikan Indonesia (UPI)',
  'Universitas Andalas (UNAND)',
  'Universitas Riau (UNRI)',
  'Universitas Sriwijaya (UNSRI)',
  'Universitas Lampung (UNILA)',
  'Universitas Jenderal Soedirman (UNSOED)',
  'Universitas Jember (UNEJ)',
  'Universitas Udayana (UNUD)',
  'Universitas Mataram (UNRAM)',
  'Universitas Sam Ratulangi (UNSRAT)',
  'Universitas Tadulako (UNTAD)',
  'Universitas Syiah Kuala (UNSYIAH)',
  'Universitas Tanjungpura (UNTAN)',
  'Universitas Mulawarman (UNMUL)',
  'Universitas Lambung Mangkurat (ULM)',
  'Universitas Cenderawasih (UNCEN)',
  'Universitas Nusa Cendana (UNDANA)',
  'Universitas Pattimura (UNPATTI)',
  'Universitas Halu Oleo (UHO)',
  'Universitas Bengkulu (UNIB)',
  'Universitas Jambi (UNJA)',
  'Universitas Palangka Raya (UPR)',
  'Universitas Trunojoyo Madura (UTM)',
  'Universitas Tidar',
  'Universitas Singaperbangsa Karawang (UNSIKA)',
  'Universitas Siliwangi (UNSIL)',
  'Universitas Sultan Ageng Tirtayasa (UNTIRTA)',
  'UPN Veteran Jakarta',
  'UPN Veteran Yogyakarta',
  'UPN Veteran Jawa Timur',
  'Institut Teknologi Sumatera (ITERA)',
  'Institut Teknologi Kalimantan (ITK)',
  'UIN Syarif Hidayatullah Jakarta',
  'UIN Sunan Kalijaga Yogyakarta',
  'UIN Sunan Gunung Djati Bandung',
  'UIN Maulana Malik Ibrahim Malang',
  'UIN Sunan Ampel Surabaya',
  'UIN Walisongo Semarang',
  'UIN Ar-Raniry Banda Aceh',
  'UIN Alauddin Makassar',
  'Universitas Bina Nusantara (BINUS)',
  'Telkom University',
  'Universitas Pelita Harapan',
  'Universitas Katolik Indonesia Atma Jaya',
  'Universitas Atma Jaya Yogyakarta (UAJY)',
  'Universitas Katolik Parahyangan (UNPAR)',
  'Universitas Kristen Petra',
  'Universitas Kristen Satya Wacana (UKSW)',
  'Universitas Kristen Maranatha',
  'Universitas Trisakti',
  'Universitas Tarumanagara (UNTAR)',
  'Universitas Gunadarma',
  'Universitas Mercu Buana (UMB)',
  'Universitas Esa Unggul',
  'Universitas Budi Luhur',
  'Universitas Bina Sarana Informatika (BSI)',
  'Universitas Dian Nuswantoro (UDINUS)',
  'Universitas Multimedia Nusantara (UMN)',
  'Universitas Prasetiya Mulya',
  'Universitas Ciputra',
  'Universitas Surabaya (Ubaya)',
  'Universitas Muhammadiyah Yogyakarta (UMY)',
  'Universitas Muhammadiyah Surakarta (UMS)',
  'Universitas Muhammadiyah Malang (UMM)',
  'Universitas Muhammadiyah Jakarta (UMJ)',
  'Universitas Muhammadiyah Sumatera Utara (UMSU)',
  'Universitas Ahmad Dahlan (UAD)',
  'Universitas Islam Indonesia (UII)',
  'Universitas Islam Bandung (UNISBA)',
  'Universitas Nahdlatul Ulama',
  'Universitas Pancasila',
  'Universitas Nasional (UNAS)',
  'Universitas Sanata Dharma (USD)',
  'Universitas Widya Gama',
  'Universitas Pendidikan Ganesha (UNDIKSHA)',
  'Universitas Negeri Gorontalo (UNG)',
  'Universitas Khairun',
  'Universitas Bangka Belitung (UBB)',
  'Universitas Teknokrat Indonesia',
  'Institut Teknologi Telkom Purwokerto (ITTP)',
  'Institut Seni Indonesia Yogyakarta',
  'Institut Seni Budaya Indonesia Bandung',
  'Politeknik Negeri Jakarta (PNJ)',
  'Politeknik Negeri Bandung (Polban)',
  'Politeknik Elektronika Negeri Surabaya (PENS)',
  'Politeknik Negeri Semarang (Polines)',
  'STAN (Politeknik Keuangan Negara STAN)',
  'Universitas Terbuka (UT)',
];

// Abbreviation → canonical full name, used to widen search so that typing an
// acronym still finds profiles/rooms whose `university` text is the spelled-
// out name (e.g. saved before abbreviations were added, or typed by hand).
export const UNIVERSITY_ALIASES: Record<string, string> = {
  ui: 'Universitas Indonesia',
  ugm: 'Universitas Gadjah Mada',
  itb: 'Institut Teknologi Bandung',
  ipb: 'Institut Pertanian Bogor',
  its: 'Institut Teknologi Sepuluh Nopember',
  unair: 'Universitas Airlangga',
  ub: 'Universitas Brawijaya',
  undip: 'Universitas Diponegoro',
  unpad: 'Universitas Padjadjaran',
  uns: 'Universitas Sebelas Maret',
  unhas: 'Universitas Hasanuddin',
  usu: 'Universitas Sumatera Utara',
  uny: 'Universitas Negeri Yogyakarta',
  unj: 'Universitas Negeri Jakarta',
  um: 'Universitas Negeri Malang',
  unnes: 'Universitas Negeri Semarang',
  unesa: 'Universitas Negeri Surabaya',
  unimed: 'Universitas Negeri Medan',
  unp: 'Universitas Negeri Padang',
  unm: 'Universitas Negeri Makassar',
  upi: 'Universitas Pendidikan Indonesia',
  unand: 'Universitas Andalas',
  unri: 'Universitas Riau',
  unsri: 'Universitas Sriwijaya',
  unila: 'Universitas Lampung',
  unsoed: 'Universitas Jenderal Soedirman',
  unej: 'Universitas Jember',
  unud: 'Universitas Udayana',
  unram: 'Universitas Mataram',
  unsrat: 'Universitas Sam Ratulangi',
  untad: 'Universitas Tadulako',
  unsyiah: 'Universitas Syiah Kuala',
  untan: 'Universitas Tanjungpura',
  unmul: 'Universitas Mulawarman',
  ulm: 'Universitas Lambung Mangkurat',
  uncen: 'Universitas Cenderawasih',
  undana: 'Universitas Nusa Cendana',
  unpatti: 'Universitas Pattimura',
  uho: 'Universitas Halu Oleo',
  unib: 'Universitas Bengkulu',
  unja: 'Universitas Jambi',
  upr: 'Universitas Palangka Raya',
  utm: 'Universitas Trunojoyo Madura',
  unsika: 'Universitas Singaperbangsa Karawang',
  unsil: 'Universitas Siliwangi',
  untirta: 'Universitas Sultan Ageng Tirtayasa',
  itera: 'Institut Teknologi Sumatera',
  itk: 'Institut Teknologi Kalimantan',
  binus: 'Universitas Bina Nusantara',
  bsi: 'Universitas Bina Sarana Informatika',
  uajy: 'Universitas Atma Jaya Yogyakarta',
  unpar: 'Universitas Katolik Parahyangan',
  uksw: 'Universitas Kristen Satya Wacana',
  untar: 'Universitas Tarumanagara',
  umb: 'Universitas Mercu Buana',
  udinus: 'Universitas Dian Nuswantoro',
  umn: 'Universitas Multimedia Nusantara',
  ubaya: 'Universitas Surabaya',
  umy: 'Universitas Muhammadiyah Yogyakarta',
  ums: 'Universitas Muhammadiyah Surakarta',
  umm: 'Universitas Muhammadiyah Malang',
  umj: 'Universitas Muhammadiyah Jakarta',
  umsu: 'Universitas Muhammadiyah Sumatera Utara',
  uad: 'Universitas Ahmad Dahlan',
  uii: 'Universitas Islam Indonesia',
  unisba: 'Universitas Islam Bandung',
  unas: 'Universitas Nasional',
  usd: 'Universitas Sanata Dharma',
  undiksha: 'Universitas Pendidikan Ganesha',
  ung: 'Universitas Negeri Gorontalo',
  ubb: 'Universitas Bangka Belitung',
  ittp: 'Institut Teknologi Telkom Purwokerto',
  pnj: 'Politeknik Negeri Jakarta',
  polban: 'Politeknik Negeri Bandung',
  pens: 'Politeknik Elektronika Negeri Surabaya',
  polines: 'Politeknik Negeri Semarang',
  stan: 'Politeknik Keuangan Negara STAN',
  ut: 'Universitas Terbuka',
};

/**
 * Builds a Postgrest `.or()` filter string that matches `column` against the
 * raw query AND (if the query is a known abbreviation) the spelled-out name,
 * so searching "uns" also finds profiles saved as "Universitas Sebelas Maret".
 * Returns '' if there's nothing to search on.
 */
export function buildEduOrFilter(column: string, rawQuery: string): string {
  const q = rawQuery.trim();
  if (!q) return '';
  const terms = new Set<string>([q]);
  const alias = UNIVERSITY_ALIASES[q.toLowerCase()];
  if (alias) terms.add(alias);
  return [...terms].map((t) => `${column}.ilike.%${t.replace(/[%,]/g, '')}%`).join(',');
}

export const MAJORS: string[] = [
  // Teknik & Komputer
  'Teknik Informatika',
  'Sistem Informasi',
  'Ilmu Komputer',
  'Teknologi Informasi',
  'Rekayasa Perangkat Lunak',
  'Teknik Komputer',
  'Sains Data',
  'Teknik Elektro',
  'Teknik Mesin',
  'Teknik Sipil',
  'Teknik Industri',
  'Teknik Kimia',
  'Teknik Lingkungan',
  'Teknik Arsitektur',
  'Arsitektur',
  'Teknik Geodesi',
  'Teknik Geologi',
  'Teknik Perminyakan',
  'Teknik Pertambangan',
  'Teknik Metalurgi',
  'Teknik Material',
  'Teknik Fisika',
  'Teknik Biomedis',
  'Teknik Telekomunikasi',
  'Teknik Penerbangan',
  'Teknik Perkapalan',
  'Perencanaan Wilayah dan Kota',
  // MIPA
  'Matematika',
  'Fisika',
  'Kimia',
  'Biologi',
  'Statistika',
  'Aktuaria',
  'Geofisika',
  'Astronomi',
  // Kedokteran & Kesehatan
  'Pendidikan Dokter',
  'Kedokteran',
  'Kedokteran Gigi',
  'Kedokteran Hewan',
  'Farmasi',
  'Keperawatan',
  'Kebidanan',
  'Kesehatan Masyarakat',
  'Gizi',
  'Fisioterapi',
  'Teknologi Laboratorium Medis',
  'Psikologi',
  // Ekonomi & Bisnis
  'Manajemen',
  'Akuntansi',
  'Ilmu Ekonomi',
  'Ekonomi Pembangunan',
  'Ekonomi Islam',
  'Bisnis Digital',
  'Manajemen Bisnis',
  'Kewirausahaan',
  'Perbankan',
  'Keuangan',
  // Sosial & Humaniora
  'Ilmu Hukum',
  'Ilmu Komunikasi',
  'Hubungan Internasional',
  'Ilmu Politik',
  'Administrasi Publik',
  'Administrasi Bisnis',
  'Ilmu Pemerintahan',
  'Sosiologi',
  'Antropologi',
  'Ilmu Sejarah',
  'Ilmu Perpustakaan',
  'Kriminologi',
  'Kesejahteraan Sosial',
  // Sastra & Bahasa
  'Sastra Inggris',
  'Sastra Indonesia',
  'Sastra Jepang',
  'Sastra Arab',
  'Sastra Mandarin (Bahasa Mandarin)',
  'Sastra Jerman',
  'Sastra Prancis',
  'Linguistik',
  // Pendidikan
  'Pendidikan Guru Sekolah Dasar (PGSD)',
  'Pendidikan Anak Usia Dini (PAUD)',
  'Pendidikan Matematika',
  'Pendidikan Bahasa Inggris',
  'Pendidikan Bahasa Indonesia',
  'Pendidikan Biologi',
  'Pendidikan Fisika',
  'Pendidikan Kimia',
  'Pendidikan Olahraga',
  'Bimbingan dan Konseling',
  // Pertanian & Lingkungan
  'Agribisnis',
  'Agroteknologi',
  'Teknologi Pangan',
  'Ilmu dan Teknologi Pangan',
  'Peternakan',
  'Kehutanan',
  'Ilmu Kelautan',
  'Perikanan',
  'Budidaya Perairan',
  // Seni & Desain
  'Desain Komunikasi Visual (DKV)',
  'Desain Produk',
  'Desain Interior',
  'Seni Rupa',
  'Film dan Televisi',
  'Musik',
  'Seni Tari',
  // Agama
  'Pendidikan Agama Islam',
  'Hukum Keluarga Islam',
  'Ekonomi Syariah',
  'Ilmu Al-Quran dan Tafsir',
  // Lainnya
  'Pariwisata',
  'Perhotelan',
  'Ilmu Gizi',
  'Bioteknologi',
];
